plugins:
  - jekyll-remote-theme # to allow having minima v3 (see https://github.com/jekyll/minima/issues/419#issuecomment-558693485)
# to allow having minima v3 (see https://github.com/jekyll/minima/issues/419#issuecomment-558693485)
remote_theme: jekyll/minima
author:
  name: Joseph Birkner
  email: "blog@josephbirkner.com"
title: Subject of Information
description: Some personal things to share.
minima:
  skin: dark
